#!/usr/bin/env python3
from pathlib import Path

root = Path("astrix-app/pages/guardian-workspace-v2")
module = root / "guardian-beta-armour-layout.mjs"
css = root / "guardian-workspace-v2-beta.css"
index = root / "index.html"

module.write_text('function esc(value){\n  return String(value??"")\n    .replaceAll("&","&amp;")\n    .replaceAll("<","&lt;")\n    .replaceAll(">","&gt;")\n    .replaceAll(\'"\',"&quot;")\n    .replaceAll("\'","&#39;");\n}\n\nfunction iconMarkup(item,label){\n  const icon=String(item?.icon??"").trim();\n  if(!icon){\n    return \'<span class="beta-slot-glyph">◇</span>\';\n  }\n  return `<img src="${esc(icon)}" alt="${esc(label)}" title="${esc(label)}" onerror="this.style.display=\'none\'">`;\n}\n\nfunction modSlot(mod){\n  if(!mod){\n    return \'<div class="beta-armour-mod-slot empty" title="Empty armour mod slot"><span class="beta-slot-glyph">◇</span></div>\';\n  }\n\n  const name=mod.name??`Destiny mod ${mod.hash??""}`;\n  const description=mod.description??"";\n  const hash=mod.bungieHash??mod.hash??"";\n\n  return `<div class="beta-armour-mod-slot filled" title="${esc(name)}${description?` — ${esc(description)}`:""}" data-mod-hash="${esc(hash)}">${iconMarkup(mod,name)}</div>`;\n}\n\nfunction traitMarkup(item){\n  const trait=item?.intrinsicTrait;\n  if(!trait)return "";\n\n  const name=trait.name??"Exotic intrinsic trait";\n  const description=trait.description??"";\n\n  return `\n    <div class="beta-exotic-trait" title="${esc(name)}${description?` — ${esc(description)}`:""}">\n      <span class="beta-exotic-trait-icon">${iconMarkup(trait,name)}</span>\n      <span class="beta-exotic-trait-copy">\n        <small>EXOTIC TRAIT</small>\n        <b>${esc(name)}</b>\n      </span>\n    </div>\n  `;\n}\n\nfunction renderArmourDetails(armour=[]){\n  const cards=[...document.querySelectorAll(".arm-grid .arm")];\n\n  cards.forEach((card,index)=>{\n    const item=armour[index]??null;\n\n    card.querySelector(".beta-armour-functional")?.remove();\n\n    if(!item)return;\n\n    const mods=[...(item.mods??[])];\n    while(mods.length<6)mods.push(null);\n\n    const functional=document.createElement("div");\n    functional.className="beta-armour-functional";\n    functional.innerHTML=`\n      ${traitMarkup(item)}\n      <div class="beta-armour-mod-heading">\n        <span>ARMOUR MODS</span>\n        <small>6 SLOTS</small>\n      </div>\n      <div class="beta-armour-mod-grid">\n        ${mods.slice(0,6).map(modSlot).join("")}\n      </div>\n    `;\n\n    card.appendChild(functional);\n  });\n}\n\nfunction receiveGuardian(detail){\n  const armour=Array.isArray(detail?.armour)?detail.armour:[];\n  requestAnimationFrame(()=>renderArmourDetails(armour));\n}\n\ndocument.addEventListener(\n  "forge:guardian-selection-changed",\n  event=>receiveGuardian(event.detail)\n);\n\ndocument.addEventListener(\n  "forge:beta-fixture-loaded",\n  event=>receiveGuardian(event.detail)\n);\n', encoding="utf-8")

existing_css = css.read_text(encoding="utf-8") if css.exists() else ""
marker = "/* Beta equipment layout: narrower weapons, wider armour */"
if marker not in existing_css:
    css.write_text(existing_css + "\n" + '/* Beta equipment layout: narrower weapons, wider armour */\n.equip {\n  grid-template-columns: minmax(240px,.72fr) minmax(0,2.28fr) !important;\n}\n\n.equip > .eq:first-child,\n.equip > .eq:nth-child(2) {\n  min-width: 0;\n}\n\n.weap-grid {\n  gap: 7px !important;\n}\n\n.weap-grid .weap {\n  min-width: 0 !important;\n}\n\n.weap-grid .weap .art {\n  aspect-ratio: 1 / 1;\n}\n\n.weap-grid .weap .art img {\n  width: 100%;\n  height: 100%;\n  object-fit: cover;\n}\n\n.beta-armour-functional {\n  margin-top: 7px;\n  width: 100%;\n}\n\n.beta-armour-mod-heading {\n  display: flex;\n  align-items: center;\n  justify-content: space-between;\n  margin: 5px 1px 4px;\n  font-size: 8px;\n  letter-spacing: .08em;\n  opacity: .78;\n}\n\n.beta-armour-mod-heading small {\n  font-size: 7px;\n  opacity: .55;\n}\n\n.beta-armour-mod-grid {\n  display: grid;\n  grid-template-columns: repeat(3,minmax(0,1fr));\n  gap: 4px;\n}\n\n.beta-armour-mod-slot {\n  position: relative;\n  display: grid;\n  place-items: center;\n  aspect-ratio: 1 / 1;\n  min-width: 0;\n  border: 1px solid rgba(151,107,255,.30);\n  border-radius: 5px;\n  overflow: hidden;\n  background: linear-gradient(145deg,rgba(87,52,142,.20),rgba(15,11,27,.55));\n}\n\n.beta-armour-mod-slot.filled {\n  border-color: rgba(166,126,255,.60);\n}\n\n.beta-armour-mod-slot img {\n  width: 82%;\n  height: 82%;\n  object-fit: contain;\n}\n\n.beta-armour-mod-slot.empty {\n  opacity: .52;\n}\n\n.beta-slot-glyph {\n  font-size: 12px;\n  opacity: .42;\n}\n\n.beta-exotic-trait {\n  display: flex;\n  align-items: center;\n  gap: 6px;\n  padding: 5px 6px;\n  margin-bottom: 6px;\n  border: 1px solid rgba(232,194,91,.52);\n  border-radius: 5px;\n  background: linear-gradient(90deg,rgba(171,126,24,.16),rgba(30,22,9,.08));\n}\n\n.beta-exotic-trait-icon {\n  width: 25px;\n  height: 25px;\n  display: grid;\n  place-items: center;\n  flex: 0 0 25px;\n  overflow: hidden;\n}\n\n.beta-exotic-trait-icon img {\n  width: 100%;\n  height: 100%;\n  object-fit: contain;\n}\n\n.beta-exotic-trait-copy {\n  display: flex;\n  flex-direction: column;\n  min-width: 0;\n}\n\n.beta-exotic-trait-copy small {\n  font-size: 6px;\n  letter-spacing: .08em;\n  color: #d7b957;\n}\n\n.beta-exotic-trait-copy b {\n  font-size: 8px;\n  line-height: 1.1;\n  overflow: hidden;\n  text-overflow: ellipsis;\n  white-space: nowrap;\n}\n\n.arm-grid {\n  gap: 8px !important;\n}\n\n.arm-grid .arm {\n  min-width: 0;\n}\n' + "\n", encoding="utf-8")

html = index.read_text(encoding="utf-8")
script_tag = '<script type="module" src="./guardian-beta-armour-layout.mjs"></script>'
anchor = '<script type="module" src="./guardian-fixture-loader.mjs"></script>'

if script_tag not in html:
    if anchor not in html:
        raise SystemExit("Fixture loader script tag not found in index.html")
    html = html.replace(anchor, anchor + "\n" + script_tag, 1)
    index.write_text(html, encoding="utf-8")

print("Created:", module)
print("Updated:", css)
print("Updated:", index)
