import {loadoutIcon,bindLoadoutIconDetails} from '../../shared/loadout-icon-layout.mjs?v=20260927-adapt-1';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function renderDimComparison(build){
  const report=build?.dimAdaptation;if(!report)return '';
  const original=build.dimTarget;
  const current=[...(build.weapons||[]),...(build.armour||[]),build.subclassItem].filter(Boolean);
  const changed=report.comparisons.some(row=>String(current.find(item=>item.bucketHash===row.bucketHash)?.itemInstanceId||'')!==String(row.selected?.itemInstanceId||''));
  return `<h2>SHARED BUILD FIT</h2><p>${esc(report.sourceName)} · ${esc(report.characterClass)}</p><p>Comparison captured when this import was matched to your inventory.</p>${changed?'<p>The Working Build has changed since import. This comparison records the initial recommendation.</p>':''}<div class="apx-icon-strip" aria-label="Original Exotic and Super anchors">${(report.anchors||[]).map(item=>loadoutIcon(item)).join('')}</div><div class="apx-dim-comparison">${report.comparisons.map(row=>`<div class="apx-dim-match">${loadoutIcon(row.target,{large:true})}<span aria-hidden="true">→</span>${row.selected?loadoutIcon(row.selected,{large:true}):'<span>Missing</span>'}<div><strong>${esc(row.status==='matched'?'Same item':row.status==='substituted'?'Suggested replacement':'Original item missing')}</strong><p>${esc(row.reasons.join(' · '))}</p>${row.missingSockets.length?`<p>Unavailable sockets: ${esc(row.missingSockets.join(', '))}</p>`:''}</div></div>`).join('')}</div>${report.blockers.length?`<ul>${report.blockers.map(text=>`<li>${esc(text)}</li>`).join('')}</ul>`:''}${report.setTargets.length?`<h3>Set targets</h3><ul>${report.setTargets.map(row=>`<li>${esc(row.name)}: ${row.current}/${row.required} pieces</li>`).join('')}</ul>`:''}${report.statTargets.length?`<h3>Stat targets</h3><p>Current item totals, before changes to mods or subclass bonuses.</p><ul>${report.statTargets.map(row=>`<li>${esc(row.name)}: ${row.legacy?'Legacy target, not applied':`${row.current??'Unavailable'} · target ${row.min}–${row.max}`}</li>`).join('')}</ul>`:''}${report.parameterSteps.length?`<details><summary>Mods, cosmetics and artifact targets</summary><p>Retained from the share. Review placement, unlocks and energy costs in Destiny; these have not been applied.</p>${report.parameterSteps.map(group=>`<p>${esc(group.label)}: ${group.items.map(item=>esc(item.name)+(item.retired?' (retired)':item.availableOn?.length?` (socket option on ${esc(item.availableOn.join(', '))})`:' (placement or unlock not confirmed)')).join('; ')}</p>`).join('')}</details>`:''}<details><summary>How this fit was selected</summary><p>${esc(report.method)}</p><p>The shared original is preserved${original?' in this build':''}. A suggested replacement can differ in effects; missing Exotic effects are never treated as equivalent.</p></details>`;
}
let dispose=()=>{};
export function mountDimComparison(build,host){
  if(!host)return;dispose();host.hidden=!build?.dimAdaptation;host.innerHTML=renderDimComparison(build);dispose=bindLoadoutIconDetails(host);
}
